apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-alpha
  namespace: mercury
spec:
  replicas: 2
  selector:
    matchLabels:
      id: app-alpha
  template:
    metadata:
      labels:
        id: app-alpha
    spec:
      volumes:
      - name: logs-volume
        emptyDir: {}
      initContainers:
      - name: init-container
        image: bash:5.0.11
        command: ['bash', '-c', 'echo init > /var/log/app-alpha/index1.log']
        volumeMounts:
        - name: logs-volume
          mountPath: /var/log/app-alpha
      - name: logger-container                                              
        image: busybox:1.31.0                                          
        restartPolicy: Always                                          
        command: ["sh", "-c", "tail -f /var/log/app-alpha/index1.log"]  
        volumeMounts:                                                  
        - name: logs-volume                                                   
          mountPath: /var/log/app-alpha                                  
      containers:
      - name: app-alpha
        image: bash:5.0.11
        args: ['bash', '-c', 'while true; do echo `date`> "trace of log" >> /var/log/app-alpha/index1.log; sleep 10; done']
        volumeMounts:
        - name: logs-volume
          mountPath: /var/log/app-alpha