apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-alpha-back
    tier: back
    version: v2
  name: app-alpha-back
spec:
  replicas: 2 # Validate and change to 10
  selector:
    matchLabels:
      app: app-alpha-back
  strategy: {}
  template:
    metadata:
      labels:
        app: app-alpha-back
        tier: back
        version: v2
    spec:
      containers:
      - image: nginx:stable
        name: container-app-alpha-back
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"        
status: {}